In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\anand\anaconda3\envs\ml_python_2019\lib\site-packages (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\anand\anaconda3\envs\ml_python_2019\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in c:\users\anand\anaconda3\envs\ml_python_2019\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: pytz>=2017.3 in c:\users\anand\anaconda3\envs\ml_python_2019\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: six>=1.5 in c:\users\anand\anaconda3\envs\ml_python_2019\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [7]:
#pandas series--one-dimensional labeled array.
marks=pd.Series([85,90,78,92,88])
print(marks)#index--0,1,2,3,4,values--85,90,78,92,88

0    85
1    90
2    78
3    92
4    88
dtype: int64

In [9]:
#custom index
marks=pd.Series([85,90,78],index=["Python","Sql","Pandas"])
print(marks)

Python    85
Sql       90
Pandas    78
dtype: int64

In [11]:
#access
print(marks["Python"])

85

In [13]:
#creating a dataframe--Adataframe is similar to an excel table.
data={"Name":["Anand","Rahul","Priya","kiran"],"Age":[20,23,21,24],"Marks":[85,90,78,92]}
df=pd.DataFrame(data)
print(df)

    Name  Age  Marks
0  Anand   20     85
1  Rahul   23     90
2  Priya   21     78
3  kiran   24     92

In [15]:
#understanding DataFrame components.
#A dataframe contains-index,columns,values.
print(df.index)
print(df.columns)
print(df.values)

RangeIndex(start=0, stop=4, step=1)
Index(['Name', 'Age', 'Marks'], dtype='object')
[['Anand' 20 85]
 ['Rahul' 23 90]
 ['Priya' 21 78]
 ['kiran' 24 92]]

In [19]:
# # reading csv files--this is one of the most important pandas operations.
# df=pd.read_csv("students.csv")
# display-print(df)
# first 5 rows--df.head(5)
# last 5 rows --df.tail(5)
# first 10 rows--df.head(10)
# last 10 rows--df.head(10)

In [21]:
# #reading excel files.
# df=pd.read_excel("student.xlsx")
# specific sheet-
# df=pd.read_excel("student.xlsx",sheet_name=:Sheet1")

In [23]:
# #reading JSON
# df.read_json("students.json")

In [25]:
# #reading sql data.
# import pandas as pd
# import sqlite3
# connection=sqlite3.connect("company.db")
# df=pd.read_sql("SELECT*FROM employees",connection)
# print(df) #here this is very useful when combining sql+python+pandas.

In [27]:
# #inspecting data--after loading a dataset,the first thing you should do is understand it.
# head()--df.head()
# tail()--df.tail()
# shape--print(df.shape)--Ex-1000 rows c 8 columns

In [29]:
# #info()--very important for data analysis.
# #it tells--number of rows,columns,data types,non-null values,memory usage.
# df.info()

In [33]:
# #describe()--used for statistical summary.it provides(mean,count,standaed deviation,minimum,25%,50%,75%,maximum)
# df["salary"].describe()

In [35]:
print(df.columns)

Index(['Name', 'Age', 'Marks'], dtype='object')

In [37]:
#checking data types.
print(df.dtypes)

Name     object
Age       int64
Marks     int64
dtype: object

In [41]:
#selecting a column
df["Name"]
#Multiple columns.
df[["Name","Age"]]

    Name  Age
0  Anand   20
1  Rahul   23
2  Priya   21
3  kiran   24

In [43]:
#selecting rows--using iloc(iloc uses numerical positions)
df.iloc[0]
#first 3 row
df.iloc[0:3]

    Name  Age  Marks
0  Anand   20     85
1  Rahul   23     90
2  Priya   21     78

In [45]:
#using loc.loc uses labels.
df.loc[0]

Name     Anand
Age         20
Marks       85
Name: 0, dtype: object

In [47]:
#multiple rows.
df.loc[0:2]

    Name  Age  Marks
0  Anand   20     85
1  Rahul   23     90
2  Priya   21     78

In [51]:
#specific columns.
df.loc[0:2,["Name","Marks"]]

    Name  Marks
0  Anand     85
1  Rahul     90
2  Priya     78

In [53]:
# #difference b/w loc and iloc 
# loc-label based,df.loc[2],uses row /column labels
# iloc--position based,df.iloc[2,uses integer positions

In [19]:
#filtering data.
df=pd.DataFrame({"Name":["Anand","Rahul","Priya","kiran"],"Age":[22,25,21,30],"Salary":[30000,45000,28000,60000]})
#find people whose salary is greater than 40000.
result=df[df["Salary"]>40000]
print(result)

    Name  Age  Salary
1  Rahul   25   45000
3  kiran   30   60000

In [63]:
#multiple conditions,And ,or
df[(df["Age"]>22)&(df["Salary"]>40000)]

    Name  Age  Salary
1  Rahul   25   45000
3  kiran   30   60000

In [67]:
# #isin()--find employees from selected departments.
# df[df["department".isin(["IT","HR"])]]

In [69]:
#b/w(). this selects age from 20 to 25.
df[df["Age"].between(20,25)]

    Name  Age  Salary
0  Anand   22   30000
1  Rahul   25   45000
2  Priya   21   28000

In [71]:
#sorting data-Asending.
df.sort_values("Salary")

    Name  Age  Salary
2  Priya   21   28000
0  Anand   22   30000
1  Rahul   25   45000
3  kiran   30   60000

In [75]:
#Desending.
df.sort_values("Salary",ascending=False)

    Name  Age  Salary
3  kiran   30   60000
1  Rahul   25   45000
0  Anand   22   30000
2  Priya   21   28000

In [79]:
#multiple columns.
df.sort_values(["Name","Salary"],ascending=[True,False])

    Name  Age  Salary
0  Anand   22   30000
2  Priya   21   28000
1  Rahul   25   45000
3  kiran   30   60000

In [9]:
# # #isin()
# df=df[df["Name"].isin(["Priya","kiran"])]

In [5]:
#filtering data.
df=pd.DataFrame({"Name":["Anand","Rahul","Priya","kiran"],"Age":[22,25,21,30],"Salary":[30000,45000,28000,60000]})
#find people whose salary is greater than 40000.
result=df[df["Salary"]>40000]
print(result)

    Name  Age  Salary
1  Rahul   25   45000
3  kiran   30   60000

In [7]:
#Adding a New Column.
import pandas as pd
df["Bonus"]=df["Salary"]*0.10

In [13]:
#multiple conditions
df[
    (df["Age"] > 22) &
    (df["Salary"] > 40000)
]

    Name  Age  Salary   Bonus
1  Rahul   25   45000  4500.0
3  kiran   30   60000  6000.0

In [17]:
df[df["Age"].between(20, 25)]

    Name  Age  Salary   Bonus
0  Anand   22   30000  3000.0
1  Rahul   25   45000  4500.0
2  Priya   21   28000  2800.0

In [19]:
df.sort_values("Salary")

    Name  Age  Salary   Bonus
2  Priya   21   28000  2800.0
0  Anand   22   30000  3000.0
1  Rahul   25   45000  4500.0
3  kiran   30   60000  6000.0

In [23]:
#multiple columns.
df.sort_values(
    ["Name", "Salary"],
    ascending=[True, False]
)

    Name  Age  Salary   Bonus
0  Anand   22   30000  3000.0
2  Priya   21   28000  2800.0
1  Rahul   25   45000  4500.0
3  kiran   30   60000  6000.0

In [25]:
#Adding a New Column.
df["Bonus"]=df["Salary"]*0.10

In [27]:
df

    Name  Age  Salary   Bonus
0  Anand   22   30000  3000.0
1  Rahul   25   45000  4500.0
2  Priya   21   28000  2800.0
3  kiran   30   60000  6000.0

In [31]:
#updating a column.
df["Salary"] = df["Salary"] + 5000
df

    Name  Age  Salary   Bonus
0  Anand   22   40000  3000.0
1  Rahul   25   55000  4500.0
2  Priya   21   38000  2800.0
3  kiran   30   70000  6000.0

In [35]:
#renaming columns.
df.rename(columns={"Salary":"Annual Salary"},inplace=True)
df

    Name  Age  Annual Salary   Bonus
0  Anand   22          40000  3000.0
1  Rahul   25          55000  4500.0
2  Priya   21          38000  2800.0
3  kiran   30          70000  6000.0

In [37]:
df.rename(columns={"Salary":"Annual Salary"})
df

    Name  Age  Annual Salary   Bonus
0  Anand   22          40000  3000.0
1  Rahul   25          55000  4500.0
2  Priya   21          38000  2800.0
3  kiran   30          70000  6000.0

In [39]:
#multiple column.
df.rename(
    columns={
        "Name": "Employee_Name",
        "Age": "Employee_Age"
    },
    inplace=True
)

In [41]:
df

  Employee_Name  Employee_Age  Annual Salary   Bonus
0         Anand            22          40000  3000.0
1         Rahul            25          55000  4500.0
2         Priya            21          38000  2800.0
3         kiran            30          70000  6000.0

In [45]:
#Droping Columns.
df.drop("Employee_Age",axis=1)
df

  Employee_Name  Employee_Age  Annual Salary   Bonus
0         Anand            22          40000  3000.0
1         Rahul            25          55000  4500.0
2         Priya            21          38000  2800.0
3         kiran            30          70000  6000.0

In [47]:
df.drop(0)

  Employee_Name  Employee_Age  Annual Salary   Bonus
1         Rahul            25          55000  4500.0
2         Priya            21          38000  2800.0
3         kiran            30          70000  6000.0

In [49]:
df.drop([0,2])

  Employee_Name  Employee_Age  Annual Salary   Bonus
1         Rahul            25          55000  4500.0
3         kiran            30          70000  6000.0

In [51]:
#missing values.
df.isnull()

   Employee_Name  Employee_Age  Annual Salary  Bonus
0          False         False          False  False
1          False         False          False  False
2          False         False          False  False
3          False         False          False  False

In [53]:
#count.
df.isnull().sum()

Employee_Name    0
Employee_Age     0
Annual Salary    0
Bonus            0
dtype: int64

In [55]:
#alternative.
df.isna().sum()

Employee_Name    0
Employee_Age     0
Annual Salary    0
Bonus            0
dtype: int64

In [57]:
#Removing Missing Values.
df.dropna()

  Employee_Name  Employee_Age  Annual Salary   Bonus
0         Anand            22          40000  3000.0
1         Rahul            25          55000  4500.0
2         Priya            21          38000  2800.0
3         kiran            30          70000  6000.0

In [61]:
#remove rows containing null values.
df.dropna(inplace=True)
df

  Employee_Name  Employee_Age  Annual Salary   Bonus
0         Anand            22          40000  3000.0
1         Rahul            25          55000  4500.0
2         Priya            21          38000  2800.0
3         kiran            30          70000  6000.0

In [65]:
#Filling Missing Values.
df["Employee_Age"].fillna(25)

0    22
1    25
2    21
3    30
Name: Employee_Age, dtype: int64

In [69]:
#using mean Values.
df["Employee_Name"].fillna(df["Employee_Age"].mean(),inplace=True)
df

  Employee_Name  Employee_Age  Annual Salary   Bonus
0         Anand            22          40000  3000.0
1         Rahul            25          55000  4500.0
2         Priya            21          38000  2800.0
3         kiran            30          70000  6000.0

In [73]:
df["Annual Salary"].fillna(df["Annual Salary"].mean(),inplace=True)
df

  Employee_Name  Employee_Age  Annual Salary   Bonus
0         Anand            22          40000  3000.0
1         Rahul            25          55000  4500.0
2         Priya            21          38000  2800.0
3         kiran            30          70000  6000.0

In [77]:
#forward Fill.--it uses the previous value.
df.fillna(method="ffill")

  Employee_Name  Employee_Age  Annual Salary   Bonus
0         Anand            22          40000  3000.0
1         Rahul            25          55000  4500.0
2         Priya            21          38000  2800.0
3         kiran            30          70000  6000.0

In [81]:
#backward Fill.--it uses the next available value.
df.fillna(method="bfill")
df

  Employee_Name  Employee_Age  Annual Salary   Bonus
0         Anand            22          40000  3000.0
1         Rahul            25          55000  4500.0
2         Priya            21          38000  2800.0
3         kiran            30          70000  6000.0

In [83]:
#Duplicate Data.
df.duplicated()

0    False
1    False
2    False
3    False
dtype: bool

In [89]:
df.duplicated().sum()

0

In [93]:
df.drop_duplicates(inplace=True)
df

  Employee_Name  Employee_Age  Annual Salary   Bonus
0         Anand            22          40000  3000.0
1         Rahul            25          55000  4500.0
2         Priya            21          38000  2800.0
3         kiran            30          70000  6000.0

In [95]:
#unique values.
df["Employee_Name"].unique()

array(['Anand', 'Rahul', 'Priya', 'kiran'], dtype=object)

In [97]:
#Number of unique values.
df["Employee_Name"].nunique()

4

In [101]:
#Frequency of Values.--very useful for categorical analysis.
df["Employee_Name"].value_counts()

Anand    1
Rahul    1
Priya    1
kiran    1
Name: Employee_Name, dtype: int64

In [103]:
#String Operations.
#convert names to uppercase.
df["Employee_Name"].str.upper()

0    ANAND
1    RAHUL
2    PRIYA
3    KIRAN
Name: Employee_Name, dtype: object

In [105]:
#lower case.
df["Employee_Name"].str.lower()

0    anand
1    rahul
2    priya
3    kiran
Name: Employee_Name, dtype: object

In [107]:
#length.
df["Employee_Name"].str.len()

0    5
1    5
2    5
3    5
Name: Employee_Name, dtype: int64

In [109]:
#contains.
df[df["Employee_Name"].str.contains("an")]

  Employee_Name  Employee_Age  Annual Salary   Bonus
0         Anand            22          40000  3000.0
3         kiran            30          70000  6000.0

In [111]:
#replace.
df["Employee_Name"].str.replace("Anand", "ANAND")

0    ANAND
1    Rahul
2    Priya
3    kiran
Name: Employee_Name, dtype: object

In [125]:
#apply()--apply a function to a column.
def Annual_salary_category(Annual_salary):
    if Annual_salary >= 50000:
        return "High"
    else:
        return "Low"

df["Category"] = df["Annual_Salary"].apply(
    Annual salary_category
)

SyntaxError: invalid syntax (145852466.py, line 9)